### ISSUE TITLE
add rest api to get menu comment details

### ISSUE THREAD

**Issue by rahulsah** [rahulsah/menuAdvisorUI#11]
current rest api to get menu details is 
 'https://nodejs-menuadvisor.rhcloud.com/api/menu?menuid='+menuid;
It takes menuId as query parameter. However when in rating page there is no menu id. This is because the menu items might not have been populated in our database. Moreover the list for rating page is brought from locu which does not have menuId.

Now since we are navigating to menuDetails page after submit button of rating page is clicked...we need a way to get the menudetails when there is no menu id. This can be done if we add a rest api which takes restaurant id & menu name as query parameters. Eg.

 https://nodejs-menuadvisor.rhcloud.com/api/menu?restId=1234&menuName=dosa

Output of this should be same as that of 
 'https://nodejs-menuadvisor.rhcloud.com/api/menu?menuid='+menuid;

**Comment by wewintechnologies** [comment]
Let's discuss this before we work on it. We can achieve above without developing a different rest api.
