### ISSUE TITLE
in main page put the name of the nearest restaurent by default

### ISSUE THREAD

**Issue by rahulsah** [rahulsah/menuAdvisorUI#24]

**Comment by wewintechnologies** [comment]
We already have code that sets the name of the nearest restaurant by default. If your at home it won't get set as there is no way to guess which is the nearest using locu APIs. But if your at any restaurant, it gets set to the restaurant name your in.

**Comment by wewintechnologies** [comment]
Look at the code in setDefaultRestaurantBasedOnCurrentLocation, if ok with it close this.
