### ISSUE TITLE
remove popus on app launch

### ISSUE THREAD

**Issue by rahulsah** [rahulsah/menuAdvisorUI#32]
popup#1 : http://localhost:58888" would like to use your current location

**Comment by wewintechnologies** [comment]
popup#1 is a security popup that cannot be removed for privacy reasons. It has to be renamed to something more friendly than http://localhost.

**Comment by rahulsah** [comment]
This is not correct. You never get this popup when you open other apps which require your location. In our app everytime  you restart the app there is a popup.

**Comment by wewintechnologies** [comment]
Every app has to ask permission atleast once. I didn't know we are showing every time we restart. We have figure out how to show prompt only once.

**Comment by wewintechnologies** [comment]
While building the app we need to select for location services. This solves this issue.
